TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.05
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4
  acc_lim_x: 1.0
  acc_lim_theta: 1.0
  dva: true
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  sim_time: 1.0
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.01
  holonomic_robot: false