footprint: [[-0.15,-0.15], [0.15,-0.15], [0.15,0.15], [-0.15,0.15]]
inflation_radius: 0.3

observation_sources: laser
laser: {topic: scan, sensor_frame: lidar_frame, data_type: LaserScan,
        marking: true, clearing: true}
transform_tolerance: 1

obstacle_range: 2.5
raytrace_range: 3.0
max_obstacle_height: 0.6
min_obstacle_height: 0.0

plugins:
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
